FROM node:20-alpine AS build
ARG REACT_APP_AUTH0_DOMAIN
ARG REACT_APP_AUTH0_CLIENT_ID
ARG REACT_APP_AUTH0_AUDIENCE
ARG REACT_APP_MINIO_CREDS_ACCESS_KEY
ARG REACT_APP_MINIO_CREDS_SECRET_KEY
ARG REACT_APP_API_LOCATION
ARG REACT_APP_APP_ORIGIN
ARG REACT_APP_BUCKET_NAME
ARG REACT_APP_S3_ENDPOINT
ARG REACT_APP_S3_REGION
ARG REACT_APP_S3_FORCE_PATH_STYLE
ARG REACT_APP_EMAILJS_SERVICE_ID
ARG REACT_APP_EMAILJS_TEMPLATE_ID
ARG REACT_APP_EMAILJS_USER_ID
ENV VITE_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
ENV VITE_AUTH0_CLIENT_ID=${REACT_APP_AUTH0_CLIENT_ID}
ENV VITE_AUTH0_AUDIENCE=${REACT_APP_AUTH0_AUDIENCE}
ENV VITE_MINIO_CREDS_ACCESS_KEY=${REACT_APP_MINIO_CREDS_ACCESS_KEY}
ENV VITE_MINIO_CREDS_SECRET_KEY=${REACT_APP_MINIO_CREDS_SECRET_KEY}
ENV VITE_API_LOCATION=${REACT_APP_API_LOCATION}
ENV VITE_APP_ORIGIN=${REACT_APP_APP_ORIGIN}
ENV VITE_BUCKET_NAME=${REACT_APP_BUCKET_NAME}
ENV VITE_S3_ENDPOINT=${REACT_APP_S3_ENDPOINT}
ENV VITE_S3_REGION=${REACT_APP_S3_REGION}
ENV VITE_S3_FORCE_PATH_STYLE=${REACT_APP_S3_FORCE_PATH_STYLE}
ENV VITE_EMAILJS_SERVICE_ID=${REACT_APP_EMAILJS_SERVICE_ID}
ENV VITE_EMAILJS_TEMPLATE_ID=${REACT_APP_EMAILJS_TEMPLATE_ID}
ENV VITE_EMAILJS_USER_ID=${REACT_APP_EMAILJS_USER_ID}
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
RUN npm run build


FROM nginx:latest
COPY --from=build /app/dist /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
