on:
  release:
    types: [published]

name: tag
permissions:
  contents: write
  id-token: write
jobs:
  publish-nexus-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Change Tag
        run: |
          echo "GIT_TAG=$(echo "${{ github.ref_name }}" | sed -e 's/+/-/g')" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: kbrighton/nexusfrontend:${{ env.GIT_TAG }}
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
          build-args: |
            TAG=${{ github.ref_name }}
          secrets: |
            VITE_AUTH0_DOMAIN=${{ secrets.REACT_APP_AUTH0_DOMAIN }}
            VITE_AUTH0_CLIENT_ID=${{ secrets.REACT_APP_AUTH0_CLIENT_ID }}
            VITE_AUTH0_AUDIENCE=${{ secrets.REACT_APP_AUTH0_AUDIENCE }}
            VITE_FARO_URL=${{ secrets.REACT_APP_FARO_URL }}
            VITE_FARO_APP_NAME=${{ secrets.REACT_APP_FARO_NAME }}
            VITE_FARO_APP_VERSION=${{ secrets.REACT_APP_FARO_VERSION }}
            VITE_FARO_ENV=${{ secrets.REACT_APP_FARO_ENV }}
            VITE_MINIO_CREDS_ACCESS_KEY=${{ secrets.REACT_APP_MINIO_CREDS_ACCESS_KEY }}
            VITE_MINIO_CREDS_SECRET_KEY=${{ secrets.REACT_APP_MINIO_CREDS_SECRET_KEY }}

