on:
  release:
    types: [published]

name: tag
permissions:
  contents: write
  id-token: write
jobs:
  publish-nexus-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change Tag
        run: |
          echo "GIT_TAG=$(echo "${{ github.ref_name }}" | sed -e 's/+/-/g')" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build container image
        uses: docker/build-push-action@v6
        env:
          REACT_APP_AUTH0_DOMAIN: ${{ secret.REACT_APP_AUTH0_DOMAIN }}
          REACT_APP_AUTH0_CLIENT_ID: ${{ secret.REACT_APP_AUTH0_CLIENT_ID }}
          REACT_APP_AUTH0_AUDIENCE: ${{ secret.REACT_APP_AUTH0_AUDIENCE }}
          REACT_APP_MINIO_CREDS_ACCESS_KEY: ${{ secret.REACT_APP_MINIO_CREDS_ACCESS_KEY }}
          REACT_APP_MINIO_CREDS_SECRET_KEY: ${{ secret.REACT_APP_MINIO_CREDS_SECRET_KEY }}
        with:
          context: .
          push: true
          tags: kbrighton/nexusfrontend:${{ env.GIT_TAG }}
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
          build-args: |
            TAG=${{ github.ref_name }}
